### ISSUE TITLE
Research on Testing

### ISSUE THREAD

**Issue by yilmazvolkan** [bounswe/bounswe2019group8#117] opened 2019-10-02 15:43 UTC
**Actions:**
1. Learn the details about testing procedure and required technologies.

**Deadline:** 05.10.2019 - 23.59

**Comment by furkanaydar** [comment] 2019-10-02 18:38
Since we decided to use Spring as our backend framework, we can use the Spring Boot testing. See https://www.baeldung.com/spring-boot-testing

**Comment by cerentahtasiz** [comment] 2019-10-04 07:16
I suggest we create new issues each time a testing is required and assign it to only one person. Everyone doing some part of the testing is better than permanent testers, in my opinion.

As professor advised, everyone can write their own unit tests. For the additional testing methods,, we can use regression testing or integration testing.

**Integration testing** is the phase in software testing in which individual software modules are combined and tested as a group. Integration testing is conducted to evaluate the compliance of a system or component with specified functional requirements. It occurs after unit testing.

**Regression testing** is re-running functional and non-functional tests to ensure that previously developed and tested software still performs after a change.

For mobile, I suggest we use JUnit for unit testing. We can use kotlintest framework. See https://github.com/kotlintest/kotlintest .

**Comment by sercanersoy** [comment] 2019-10-04 20:10
I agree to what Ceren says.

Everyone can write their own unit tests.

Integration tests can be assigned to 1 or 2 people when needed. Also, I think it will be more appropriate that these assignees are different each time.

**Comment by sercanersoy** [comment] 2019-10-04 21:43
We will discuss further in the meeting, adding this to agenda and closing the issue.

**Closed by sercanersoy** 2019-10-04 21:43 UTC
Labels: Effort: Medium, Priority: High, Status: Review Needed, Type: Research
